# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'clean-gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(720, 450)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.dropShadowFrame = QtWidgets.QFrame(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.dropShadowFrame.setFont(font)
        self.dropShadowFrame.setStyleSheet("QFrame{\n"
"    background-color: rgb(252, 255, 0);\n"
"    color: rgb(25, 0, 255);\n"
"    border-radius:10px;    \n"
"}\n"
"QPushButton {\n"
"    border-radius:10px;\n"
"    background-color: rgb(120, 134, 255);\n"
"    color: rgb(247, 255, 148);\n"
"}\n"
"")
        self.dropShadowFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.dropShadowFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.dropShadowFrame.setObjectName("dropShadowFrame")
        self.label_logo = QtWidgets.QLabel(self.dropShadowFrame)
        self.label_logo.setGeometry(QtCore.QRect(10, 80, 461, 161))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_logo.setFont(font)
        self.label_logo.setStyleSheet("QLabel{\n"
"    border-radius:100px;\n"
"}")
        self.label_logo.setText("")
        self.label_logo.setPixmap(QtGui.QPixmap("../../../../Downloads/15747324_10154960500613313_463244660824628874_n.jpg"))
        self.label_logo.setScaledContents(True)
        self.label_logo.setObjectName("label_logo")
        self.label_InternetStatus = QtWidgets.QLabel(self.dropShadowFrame)
        self.label_InternetStatus.setGeometry(QtCore.QRect(550, 30, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(15)
        self.label_InternetStatus.setFont(font)
        self.label_InternetStatus.setObjectName("label_InternetStatus")
        self.buttton_GenerateInvoices = QtWidgets.QPushButton(self.dropShadowFrame)
        self.buttton_GenerateInvoices.setGeometry(QtCore.QRect(500, 140, 180, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        self.buttton_GenerateInvoices.setFont(font)
        self.buttton_GenerateInvoices.setStyleSheet("QPushButton {\n"
"    border-radius:10px;\n"
"    background-color: rgb(120, 134, 255);\n"
"    color: rgb(247, 255, 148);\n"
"}")
        self.buttton_GenerateInvoices.setObjectName("buttton_GenerateInvoices")
        self.label_FileSelected = QtWidgets.QLabel(self.dropShadowFrame)
        self.label_FileSelected.setGeometry(QtCore.QRect(10, 250, 175, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(18)
        self.label_FileSelected.setFont(font)
        self.label_FileSelected.setObjectName("label_FileSelected")
        self.label_progress = QtWidgets.QLabel(self.dropShadowFrame)
        self.label_progress.setGeometry(QtCore.QRect(640, 260, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(18)
        self.label_progress.setFont(font)
        self.label_progress.setObjectName("label_progress")
        self.progressBar = QtWidgets.QProgressBar(self.dropShadowFrame)
        self.progressBar.setEnabled(True)
        self.progressBar.setGeometry(QtCore.QRect(20, 310, 651, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.progressBar.setFont(font)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(True)
        self.progressBar.setObjectName("progressBar")
        self.button_SelectSpreadsheet = QtWidgets.QPushButton(self.dropShadowFrame)
        self.button_SelectSpreadsheet.setGeometry(QtCore.QRect(500, 80, 180, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        self.button_SelectSpreadsheet.setFont(font)
        self.button_SelectSpreadsheet.setObjectName("button_SelectSpreadsheet")
        self.label_Contents = QtWidgets.QLabel(self.dropShadowFrame)
        self.label_Contents.setGeometry(QtCore.QRect(530, 360, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_Contents.setFont(font)
        self.label_Contents.setAutoFillBackground(False)
        self.label_Contents.setWordWrap(True)
        self.label_Contents.setObjectName("label_Contents")
        self.label_about = QtWidgets.QLabel(self.dropShadowFrame)
        self.label_about.setGeometry(QtCore.QRect(330, 250, 245, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(18)
        self.label_about.setFont(font)
        self.label_about.setObjectName("label_about")
        self.button_Exit = QtWidgets.QPushButton(self.dropShadowFrame)
        self.button_Exit.setGeometry(QtCore.QRect(500, 200, 180, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        self.button_Exit.setFont(font)
        self.button_Exit.setStyleSheet("")
        self.button_Exit.setObjectName("button_Exit")
        self.label_InternetStatus_2 = QtWidgets.QLabel(self.dropShadowFrame)
        self.label_InternetStatus_2.setGeometry(QtCore.QRect(20, 10, 361, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(34)
        self.label_InternetStatus_2.setFont(font)
        self.label_InternetStatus_2.setObjectName("label_InternetStatus_2")
        self.verticalLayout.addWidget(self.dropShadowFrame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 720, 24))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menuBar)
        self.actionSpreadsheet = QtWidgets.QAction(MainWindow)
        self.actionSpreadsheet.setObjectName("actionSpreadsheet")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.action_Open = QtWidgets.QAction(MainWindow)
        self.action_Open.setObjectName("action_Open")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.menuFile.addAction(self.action_Open)
        self.menuBar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Burd"))
        self.label_InternetStatus.setText(_translate("MainWindow", "Internet: Unknown"))
        self.buttton_GenerateInvoices.setText(_translate("MainWindow", "Generate Invoices"))
        self.label_FileSelected.setText(_translate("MainWindow", "File: No file selected"))
        self.label_progress.setText(_translate("MainWindow", "0%"))
        self.button_SelectSpreadsheet.setText(_translate("MainWindow", "Select Spreadsheet"))
        self.label_Contents.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#727272;\">Created</span><span style=\" color:#727272;\"> by Cal - V1.1</span></p></body></html>"))
        self.label_about.setText(_translate("MainWindow", "Waiting for you to select file..."))
        self.button_Exit.setText(_translate("MainWindow", "Exit"))
        self.label_InternetStatus_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">INVOICE </span>GENERATOR</p></body></html>"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionSpreadsheet.setText(_translate("MainWindow", "Spreadsheet"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.action_Open.setText(_translate("MainWindow", "Open"))
        self.action_Open.setStatusTip(_translate("MainWindow", "Open spreadsheet file"))
        self.action_Open.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSave.setText(_translate("MainWindow", "Save"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
