# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'load-screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SplashScreen(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(720, 450)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.dropShadowFrame = QtWidgets.QFrame(self.centralwidget)
        self.dropShadowFrame.setStyleSheet("QFrame{\n"
"    background-color: rgb(56, 59, 89);\n"
"    color: rgb(96, 198, 54);\n"
"    border-radius: 10px\n"
"}")
        self.dropShadowFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.dropShadowFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.dropShadowFrame.setObjectName("dropShadowFrame")
        self.label_appName = QtWidgets.QLabel(self.dropShadowFrame)
        self.label_appName.setGeometry(QtCore.QRect(0, 130, 701, 81))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(50)
        self.label_appName.setFont(font)
        self.label_appName.setAlignment(QtCore.Qt.AlignCenter)
        self.label_appName.setObjectName("label_appName")
        self.label_description = QtWidgets.QLabel(self.dropShadowFrame)
        self.label_description.setGeometry(QtCore.QRect(0, 200, 691, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label_description.setFont(font)
        self.label_description.setStyleSheet("color: rgb(32, 162, 11);")
        self.label_description.setAlignment(QtCore.Qt.AlignCenter)
        self.label_description.setObjectName("label_description")
        self.progressBar = QtWidgets.QProgressBar(self.dropShadowFrame)
        self.progressBar.setGeometry(QtCore.QRect(50, 290, 591, 81))
        self.progressBar.setStyleSheet("QProgressBar{\n"
"    background-color: rgb(0, 154, 0);\n"
"    color: rgb(200, 200, 200);\n"
"    border-style: none;\n"
"    border-radius: 10px\n"
"    text-align: center;\n"
"}\n"
"\n"
"QProgressBar::chunk{\n"
"    border-radius: 10px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.00492611, y1:0.584818, x2:1, y2:0.585227, stop:0 rgba(36, 197, 0, 255), stop:1 rgba(63, 70, 255, 255));\n"
"}")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setObjectName("progressBar")
        self.label_loading = QtWidgets.QLabel(self.dropShadowFrame)
        self.label_loading.setGeometry(QtCore.QRect(10, 350, 701, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label_loading.setFont(font)
        self.label_loading.setStyleSheet("color: rgb(32, 162, 11);")
        self.label_loading.setAlignment(QtCore.Qt.AlignCenter)
        self.label_loading.setObjectName("label_loading")
        self.label_credits = QtWidgets.QLabel(self.dropShadowFrame)
        self.label_credits.setGeometry(QtCore.QRect(0, 390, 691, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label_credits.setFont(font)
        self.label_credits.setStyleSheet("color: rgb(32, 162, 11);")
        self.label_credits.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_credits.setObjectName("label_credits")
        self.verticalLayout.addWidget(self.dropShadowFrame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Loading Screen"))
        self.label_appName.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">INVOICE</span> GENERATOR</p></body></html>"))
        self.label_description.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:13pt; font-weight:600;\">Generating</span><span style=\" font-size:13pt;\"> Company Invoices</span></p></body></html>"))
        self.label_loading.setText(_translate("MainWindow", "<html><head/><body><p>Loading...</p></body></html>"))
        self.label_credits.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Created: </span>Thomas Stevens</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
