# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI Layouts/loading_screen2.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(746, 470)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.dropShadowFrame = QtWidgets.QFrame(self.centralwidget)
        self.dropShadowFrame.setGeometry(QtCore.QRect(10, 10, 726, 449))
        self.dropShadowFrame.setStyleSheet("QFrame{\n"
"    \n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(255, 81, 0);\n"
"    border-radius: 10px\n"
"}")
        self.dropShadowFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.dropShadowFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.dropShadowFrame.setObjectName("dropShadowFrame")
        self.layoutWidget = QtWidgets.QWidget(self.dropShadowFrame)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 711, 431))
        self.layoutWidget.setObjectName("layoutWidget")
        self.Load = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.Load.setContentsMargins(0, 0, 0, 0)
        self.Load.setObjectName("Load")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.Load.addItem(spacerItem)
        self.label_appName = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(50)
        font.setKerning(True)
        self.label_appName.setFont(font)
        self.label_appName.setAlignment(QtCore.Qt.AlignCenter)
        self.label_appName.setObjectName("label_appName")
        self.Load.addWidget(self.label_appName)
        self.label_description = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label_description.setFont(font)
        self.label_description.setStyleSheet("QLabel{\n"
"    color: rgb(230, 73, 0);\n"
"}")
        self.label_description.setAlignment(QtCore.Qt.AlignCenter)
        self.label_description.setObjectName("label_description")
        self.Load.addWidget(self.label_description)
        spacerItem1 = QtWidgets.QSpacerItem(20, 72, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.Load.addItem(spacerItem1)
        self.progressBar = QtWidgets.QProgressBar(self.layoutWidget)
        self.progressBar.setStyleSheet("QProgressBar{\n"
"    background-color: rgb(0, 154, 0);\n"
"    color: rgb(200, 200, 200);\n"
"    border-style: none;\n"
"    border-radius: 10px\n"
"    text-align: center;\n"
"}\n"
"\n"
"QProgressBar::chunk{\n"
"    border-radius: 10px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.00492611, y1:0.584818, x2:1, y2:0.585227, stop:0 rgba(36, 197, 0, 255), stop:1 rgba(63, 70, 255, 255));\n"
"}")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setObjectName("progressBar")
        self.Load.addWidget(self.progressBar)
        self.label_loading = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label_loading.setFont(font)
        self.label_loading.setStyleSheet("color: rgb(255, 78, 0);")
        self.label_loading.setAlignment(QtCore.Qt.AlignCenter)
        self.label_loading.setObjectName("label_loading")
        self.Load.addWidget(self.label_loading)
        spacerItem2 = QtWidgets.QSpacerItem(20, 19, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.Load.addItem(spacerItem2)
        self.label_credits = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label_credits.setFont(font)
        self.label_credits.setStyleSheet("")
        self.label_credits.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_credits.setObjectName("label_credits")
        self.Load.addWidget(self.label_credits)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_appName.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">INVOICE</span> GENERATOR</p></body></html>"))
        self.label_description.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:13pt; font-weight:600;\">Generating</span><span style=\" font-size:13pt;\"> Company Invoices</span></p></body></html>"))
        self.label_loading.setText(_translate("MainWindow", "<html><head/><body><p>Loading...</p></body></html>"))
        self.label_credits.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Created:    </span>zardoss</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
