# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_Layout2.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(410, 579)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.dropShadowFrame = QtWidgets.QFrame(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.dropShadowFrame.setFont(font)
        self.dropShadowFrame.setStyleSheet("QFrame{\n"
"    background-color: rgb(254, 252, 255);\n"
"    color: rgb(255, 115, 0);\n"
"    border-radius:5px;    \n"
"    font: 13pt \".AppleSystemUIFont\";\n"
"}\n"
"QPushButton {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 1px solid;\n"
"    border-radius:17.4px;\n"
"    border-color:rgb(255);\n"
"    font: 12.5pt \".AppleSystemUIFont\";\n"
"}\n"
"QPushButton::hover{\n"
"    background-color: rgb(255, 142, 0);\n"
"}")
        self.dropShadowFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.dropShadowFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.dropShadowFrame.setObjectName("dropShadowFrame")
        self.gridLayout = QtWidgets.QGridLayout(self.dropShadowFrame)
        self.gridLayout.setObjectName("gridLayout")
        self.Layout = QtWidgets.QGridLayout()
        self.Layout.setObjectName("Layout")
        self.label_FileSelected = QtWidgets.QLabel(self.dropShadowFrame)
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_FileSelected.setFont(font)
        self.label_FileSelected.setObjectName("label_FileSelected")
        self.Layout.addWidget(self.label_FileSelected, 2, 0, 1, 1)
        self.label_InternetStatus = QtWidgets.QLabel(self.dropShadowFrame)
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_InternetStatus.setFont(font)
        self.label_InternetStatus.setObjectName("label_InternetStatus")
        self.Layout.addWidget(self.label_InternetStatus, 1, 0, 1, 1)
        self.label_about = QtWidgets.QLabel(self.dropShadowFrame)
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_about.setFont(font)
        self.label_about.setObjectName("label_about")
        self.Layout.addWidget(self.label_about, 3, 0, 1, 1)
        self.gridLayout.addLayout(self.Layout, 10, 0, 1, 1)
        self.Title = QtWidgets.QHBoxLayout()
        self.Title.setObjectName("Title")
        self.label_Title = QtWidgets.QLabel(self.dropShadowFrame)
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_Title.setFont(font)
        self.label_Title.setStyleSheet("QLabel{\n"
"    font: 30pt \".AppleSystemUIFont\";\n"
"}")
        self.label_Title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Title.setObjectName("label_Title")
        self.Title.addWidget(self.label_Title)
        self.gridLayout.addLayout(self.Title, 2, 0, 1, 1)
        self.progressBarLayout = QtWidgets.QHBoxLayout()
        self.progressBarLayout.setObjectName("progressBarLayout")
        self.progressBar = QtWidgets.QProgressBar(self.dropShadowFrame)
        self.progressBar.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar.sizePolicy().hasHeightForWidth())
        self.progressBar.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.progressBar.setFont(font)
        self.progressBar.setStyleSheet("QProgressBar{\n"
"    \n"
"    background-color: rgb(7, 0, 255);\n"
"}")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(True)
        self.progressBar.setObjectName("progressBar")
        self.progressBarLayout.addWidget(self.progressBar)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.progressBarLayout.addItem(spacerItem)
        self.label_progress = QtWidgets.QLabel(self.dropShadowFrame)
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_progress.setFont(font)
        self.label_progress.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_progress.setObjectName("label_progress")
        self.progressBarLayout.addWidget(self.label_progress)
        self.gridLayout.addLayout(self.progressBarLayout, 9, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_logo = QtWidgets.QLabel(self.dropShadowFrame)
        self.label_logo.setMinimumSize(QtCore.QSize(250, 120))
        self.label_logo.setMaximumSize(QtCore.QSize(350, 120))
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_logo.setFont(font)
        self.label_logo.setStyleSheet("QLabel{\n"
"    border-radius:10px;\n"
"}")
        self.label_logo.setText("")
        self.label_logo.setPixmap(QtGui.QPixmap("Images/inspiration2.jpg"))
        self.label_logo.setScaledContents(True)
        self.label_logo.setAlignment(QtCore.Qt.AlignCenter)
        self.label_logo.setObjectName("label_logo")
        self.verticalLayout_2.addWidget(self.label_logo, 0, QtCore.Qt.AlignHCenter)
        spacerItem1 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem1)
        self.button_GenerateInvoices = QtWidgets.QPushButton(self.dropShadowFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_GenerateInvoices.sizePolicy().hasHeightForWidth())
        self.button_GenerateInvoices.setSizePolicy(sizePolicy)
        self.button_GenerateInvoices.setMinimumSize(QtCore.QSize(210, 50))
        self.button_GenerateInvoices.setMaximumSize(QtCore.QSize(250, 70))
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.button_GenerateInvoices.setFont(font)
        self.button_GenerateInvoices.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_GenerateInvoices.setAutoFillBackground(False)
        self.button_GenerateInvoices.setStyleSheet("QPushButton{\n"
"    border-color: rgb(255, 142, 0);\n"
"    border-radius: 25px;\n"
"}")
        self.button_GenerateInvoices.setObjectName("button_GenerateInvoices")
        self.verticalLayout_2.addWidget(self.button_GenerateInvoices, 0, QtCore.Qt.AlignHCenter)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem2)
        self.gridLayout.addLayout(self.verticalLayout_2, 5, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem3, 11, 0, 1, 1)
        self.BottomLabels = QtWidgets.QHBoxLayout()
        self.BottomLabels.setObjectName("BottomLabels")
        self.label = QtWidgets.QLabel(self.dropShadowFrame)
        self.label.setStyleSheet("QLabel{\n"
"    color: rgb(96, 95, 95);\n"
"    font: 13pt \".AppleSystemUIFont\";\n"
"}")
        self.label.setObjectName("label")
        self.BottomLabels.addWidget(self.label)
        self.label_Contents_2 = QtWidgets.QLabel(self.dropShadowFrame)
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_Contents_2.setFont(font)
        self.label_Contents_2.setAutoFillBackground(False)
        self.label_Contents_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_Contents_2.setWordWrap(True)
        self.label_Contents_2.setObjectName("label_Contents_2")
        self.BottomLabels.addWidget(self.label_Contents_2)
        self.gridLayout.addLayout(self.BottomLabels, 12, 0, 1, 1)
        self.titlebuttons = QtWidgets.QHBoxLayout()
        self.titlebuttons.setObjectName("titlebuttons")
        self.button_exit = QtWidgets.QPushButton(self.dropShadowFrame)
        self.button_exit.setMinimumSize(QtCore.QSize(16, 16))
        self.button_exit.setMaximumSize(QtCore.QSize(16, 16))
        self.button_exit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_exit.setStyleSheet("QPushButton{\n"
"    border-radius: 7px;\n"
"    border-color: rgb(252, 70, 70);\n"
"    background-color: rgb(252, 70, 70);\n"
"}")
        self.button_exit.setText("")
        self.button_exit.setObjectName("button_exit")
        self.titlebuttons.addWidget(self.button_exit)
        self.button_minimise = QtWidgets.QPushButton(self.dropShadowFrame)
        self.button_minimise.setMinimumSize(QtCore.QSize(16, 16))
        self.button_minimise.setMaximumSize(QtCore.QSize(16, 16))
        self.button_minimise.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_minimise.setStyleSheet("QPushButton{\n"
"    border-radius: 7px;\n"
"    border-color:rgb(208, 255, 0);\n"
"    background-color: rgb(208, 255, 0);\n"
"}")
        self.button_minimise.setText("")
        self.button_minimise.setObjectName("button_minimise")
        self.titlebuttons.addWidget(self.button_minimise)
        self.button_expand = QtWidgets.QPushButton(self.dropShadowFrame)
        self.button_expand.setMinimumSize(QtCore.QSize(15, 15))
        self.button_expand.setMaximumSize(QtCore.QSize(15, 15))
        self.button_expand.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_expand.setStyleSheet("QPushButton{ \n"
"    border-radius: 7px;\n"
"    border-color:  rgb(40, 194, 49);\n"
"    background-color: rgb(40, 194, 49);\n"
"}")
        self.button_expand.setText("")
        self.button_expand.setObjectName("button_expand")
        self.titlebuttons.addWidget(self.button_expand)
        spacerItem4 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.titlebuttons.addItem(spacerItem4)
        self.gridLayout.addLayout(self.titlebuttons, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.dropShadowFrame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_FileSelected.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">File:</span> No file selected</p></body></html>"))
        self.label_InternetStatus.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Internet: </span>Unknown</p></body></html>"))
        self.label_about.setText(_translate("MainWindow", "<html><head/><body><p>When you\'re ready, click &quot;Generate&quot;</p></body></html>"))
        self.label_Title.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:36pt; font-weight:600;\">INVOICE </span><span style=\" font-size:36pt;\">GENERATOR</span></p></body></html>"))
        self.label_progress.setText(_translate("MainWindow", "0%"))
        self.button_GenerateInvoices.setAccessibleDescription(_translate("MainWindow", "0"))
        self.button_GenerateInvoices.setText(_translate("MainWindow", "Click to Generate Invoices"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p>Press <span style=\" font-weight:600;\">esc </span>to exit</p></body></html>"))
        self.label_Contents_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#727272;\">Created</span><span style=\" color:#727272;\"> by zardoss - V1.1</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
